src/objects/Sensor__c.object
<CustomObject>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Sensor</label>
    <nameField>
        <label>Sensor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sensor</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sensor_Event__c.object
<CustomObject>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Previous_Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Previous Event</label>
        <referenceTo>Sensor_Event__c</referenceTo>
        <relationshipLabel>Sensor Event</relationshipLabel>
        <relationshipName>Sensor_Event</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sensor__c</fullName>
        <label>Sensor</label>
        <referenceTo>Sensor__c</referenceTo>
        <relationshipLabel>Sensor Event</relationshipLabel>
        <relationshipName>Sensor_Event</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>x__c</fullName>
        <label>x</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>y__c</fullName>
        <label>y</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>z__c</fullName>
        <label>z</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <label>Sensor Event</label>
    <nameField>
        <label>Sensor Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sensor Event</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SensorEventService.cls
@RestResource(UrlMapping='/sensorEvents/*')
global with sharing class SensorEventService {

    public class SensorEventRequest {
        public String sensorid;
        public List<Vector> vectors;
    }

    public class Vector {
        public Decimal x;
        public Decimal y;
        public Decimal z;
    }

    @HttpPost
    global static String createSensorEvents() {
        RestRequest req = RestContext.request;
        String inputJson = req.requestBody.toString();

        SensorEventRequest request = (SensorEventRequest) JSON.deserialize(inputJson, SensorEventRequest.class);

        Sensor__c sensor;
        List<Sensor__c> sensors = [SELECT Id, Name FROM Sensor__c WHERE Name = :request.sensorid LIMIT 1];
        if (sensors.isEmpty()) {
            sensor = new Sensor__c(Name = request.sensorid);
            insert sensor;
        } else {
            sensor = sensors[0];
        }

        List<Sensor_Event__c> lastEvents = [SELECT Id, Name__c FROM Sensor_Event__c  ORDER BY Name__c DESC LIMIT 1];
        Id previousEventId;
        if (!lastEvents.isEmpty()) {
            previousEventId = lastEvents[0].Id;
        } else {
            previousEventId = null;
        }

        List<Sensor_Event__c> sensorEvents = new List<Sensor_Event__c>();
        for (Vector vector : request.vectors) {
            Sensor_Event__c event = new Sensor_Event__c(
                    Sensor__c = sensor.Id,
                    x__c = vector.x,
                    y__c = vector.y,
                    z__c = vector.z,
                    Previous_Event__c = previousEventId
            );
            sensorEvents.add(event);
        }

        insert sensorEvents;

        for (Integer i = 1; i < sensorEvents.size(); i++) {
            sensorEvents[i].Previous_Event__c = sensorEvents[i - 1].Id;
        }
        update sensorEvents;

        return 'Sensor Events created successfully';
    }
}