src/objects/Sensor__c.object
<CustomObject>
    <fields>
        <fullName>Max_Vectors_Length__c</fullName>
        <label>Max Vectors Length</label>
        <summarizedField>Sensor_Event__c.Modulus_Vector_Length__c</summarizedField>
        <summaryForeignKey>Sensor_Event__c.Sensor__c</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Sensor</label>
    <nameField>
        <label>Sensor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sensor</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sensor_Event__c.object
<CustomObject>
    <fields>
        <fullName>Sensor__c</fullName>
        <label>Sensor</label>
        <referenceTo>Sensor__c</referenceTo>
        <relationshipLabel>Sensor Event</relationshipLabel>
        <relationshipName>Sensor_Event</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>x__c</fullName>
        <label>x</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>y__c</fullName>
        <label>y</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>z__c</fullName>
        <label>z</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <label>Sensor Event</label>
    <nameField>
        <label>Sensor Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sensor Event</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SensorController.cls
public with sharing class SensorController {
    @AuraEnabled(Cacheable=true)
    public static List<Sensor__c> getSensors() {
        return [SELECT Id, Name, Max_Vectors_Length__c FROM Sensor__c];
    }

    @AuraEnabled(Cacheable=true)
    public static List<Sensor_Event__c> getSensorEvents(Id sensorId) {
        return [
                SELECT Id, x__c, y__c, z__c, Sensor__r.Max_Vectors_Length__c
                FROM Sensor_Event__c
                WHERE Sensor__c = :sensorId
        ];
    }
}