src/objects/Sensor__c.object
<CustomObject>
    <label>Sensor</label>
    <nameField>
        <label>Sensor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sensor</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sensor_Event__c.object
<CustomObject>
    <fields>
        <fullName>Sensor__c</fullName>
        <label>Sensor</label>
        <referenceTo>Sensor__c</referenceTo>
        <relationshipLabel>Sensor Event</relationshipLabel>
        <relationshipName>Sensor_Event</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>x__c</fullName>
        <label>x</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>y__c</fullName>
        <label>y</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>z__c</fullName>
        <label>z</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <label>Sensor Event</label>
    <nameField>
        <label>Sensor Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sensor Event</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestDataFactory.cls
@IsTest
public class TestDataFactory {
    public static List<Sensor__c> createSensors(Integer numberOfSensors) {
        List<Sensor__c> sensors = new List<Sensor__c>();
        for (Integer i = 0; i < numberOfSensors; i++) {
            sensors.add(new Sensor__c(Name = 'Sensor ' + i));
        }
        insert sensors;
        return sensors;
    }

    public static List<Sensor_Event__c> createSensorEvents(Id sensorId, Integer numberOfEvents) {
        List<Sensor_Event__c> events = new List<Sensor_Event__c>();
        for (Integer i = 0; i < numberOfEvents; i++) {
            events.add(new Sensor_Event__c(
                    Sensor__c = sensorId,
                    x__c = i,
                    y__c = i * 2,
                    z__c = i * 3
            ));
        }
        insert events;
        return events;
    }

    public static RestRequest createRestRequest(String jsonInput) {
        RestRequest req = new RestRequest();
        req.requestBody = Blob.valueOf(jsonInput);
        req.requestURI = '/services/apexrest/sensorEvents/';
        req.httpMethod = 'POST';
        return req;
    }
}